---
version: "3.7"

services:
    postgres:
        image: postgres:12
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: abc123        
        ports:
            - 9702:5432
        volumes:
            - ./.postgres/data:/var/lib/postgresql/data
